---
- name: Setup Punchtime
  hosts: all
  become: yes
  tasks:
    - name: Compile application
      ansible.builtin.shell: env GOOS=linux GOARCH=arm GOARM=5 go build
      delegate_to: localhost
      become: no
    - name: Install application
      ansible.builtin.copy:
        src: punchtime
        dest: /usr/local/bin/punchtime
        owner: pi
        group: pi
        mode: u=rwx,g=rx,o=rx
    - name: Install service
      ansible.builtin.copy:
        src: punchtime.service
        dest: /etc/systemd/system/punchtime.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Punchtime service
      ansible.builtin.systemd:
        name: punchtime.service
        state: stopped
        enabled: no
        daemon_reload: yes
    - name: Install timer
      ansible.builtin.copy:
        src: punchtime.timer
        dest: /etc/systemd/system/punchtime.timer
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Enable timer for punchtime
      ansible.builtin.systemd:
        name: punchtime.timer
        state: started
        enabled: yes
        daemon_reload: yes
    - name: Copy database structure
      ansible.builtin.copy:
        src: migrations/000001_initial_schema.up.sql
        dest: /usr/local/share/punchtime/structure.sql
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Setup sqlite database
      ansible.builtin.shell:
        cmd: sqlite3 /usr/local/share/punchtime/punchtime.db < /usr/local/share/punchtime/structure.sql
